language: cpp
compiler: gcc
dist: trusty
sudo: false

addons:
 apt:
  update: true
  packages:
   - cpputest
   - doxygen
   - lcov

before_install:
 - pip install --user cpp-coveralls
 - cd build

script:
 - cmake -DCMAKE_BUILD_TYPE=RELEASE ..
 - make clean
 - make

after_success:
 - cd ..
 - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
